"""Change sports to sports_id in Users

Revision ID: e38d43207fcd
Revises: 6fe77dba2676
Create Date: 2025-09-19 11:33:06.079156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e38d43207fcd'
down_revision: Union[str, Sequence[str], None] = '6fe77dba2676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sport_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_users_sports_id', 'users', 'sports', ['sport_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'favorite_sport')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_sport', sa.String(), nullable=True))
    op.drop_constraint('fk_users_sports_id', 'users', type_='foreignkey')
    op.drop_column('users', 'sport_id')
    # ### end Alembic commands ###
